# Generated by Django 3.0.5 on 2020-06-12 22:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModuleNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('webpage', models.URLField()),
                ('streetaddress', models.CharField(max_length=100)),
                ('zipcode', models.SmallIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('arenalayout', models.FileField(upload_to='arenalayouts')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shape', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('coordinates', models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm_app.RoomType')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm_app.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('module1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module1', to='vm_app.HomeModuleNames')),
                ('module2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module2', to='vm_app.HomeModuleNames')),
                ('module3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module3', to='vm_app.HomeModuleNames')),
                ('module4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module4', to='vm_app.HomeModuleNames')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('venues', models.ManyToManyField(to='vm_app.Venue')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm_app.Room')),
            ],
        ),
    ]
