# Generated by Django 3.0.5 on 2020-06-11 14:10

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='coordinates',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.'), django.core.validators.MaxLengthValidator, django.core.validators.MinLengthValidator]),
        ),
        migrations.AddField(
            model_name='room',
            name='shape',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
