# Generated by Django 3.0.5 on 2020-06-12 19:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0002_auto_20200611_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinates',
        ),
        migrations.RemoveField(
            model_name='homemodules',
            name='module1',
        ),
        migrations.RemoveField(
            model_name='homemodules',
            name='module2',
        ),
        migrations.RemoveField(
            model_name='homemodules',
            name='module3',
        ),
        migrations.RemoveField(
            model_name='homemodules',
            name='module4',
        ),
        migrations.RemoveField(
            model_name='homemodules',
            name='user',
        ),
        migrations.DeleteModel(
            name='Shape',
        ),
        migrations.AddField(
            model_name='profile',
            name='module1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module1', to='vm_app.HomeModuleNames'),
        ),
        migrations.AddField(
            model_name='profile',
            name='module2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module2', to='vm_app.HomeModuleNames'),
        ),
        migrations.AddField(
            model_name='profile',
            name='module3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module3', to='vm_app.HomeModuleNames'),
        ),
        migrations.AddField(
            model_name='profile',
            name='module4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module4', to='vm_app.HomeModuleNames'),
        ),
        migrations.AlterField(
            model_name='room',
            name='coordinates',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.DeleteModel(
            name='HomeModules',
        ),
    ]
