# Generated by Django 3.0.5 on 2020-04-29 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0002_homemodulenames'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module1', to='vm_app.HomeModuleNames')),
                ('module2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module2', to='vm_app.HomeModuleNames')),
                ('module3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module3', to='vm_app.HomeModuleNames')),
                ('module4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module4', to='vm_app.HomeModuleNames')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
