# Generated by Django 3.0.5 on 2020-06-16 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0002_auto_20200616_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_user_permissions',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user_perms', to='vm_app.Client'),
        ),
    ]
