# Generated by Django 3.0.5 on 2020-06-16 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vm_app', '0003_auto_20200616_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='users',
            field=models.ManyToManyField(related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
