# Generated by Django 3.0.5 on 2020-06-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vm_app', '0004_auto_20200616_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_user_permissions',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm_app.Client'),
        ),
        migrations.AlterField(
            model_name='client_user_permissions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user_perms', to=settings.AUTH_USER_MODEL),
        ),
    ]
