# Generated by Django 3.0.5 on 2020-06-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0005_auto_20200608_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='client',
        ),
    ]
