# Generated by Django 3.0.5 on 2020-06-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vm_app', '0005_auto_20200616_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vm_app.Client'),
        ),
    ]
